CREATE TABLE STUDENTS (
S_ID INT PRIMARY KEY,
S_NAME VARCHAR(100) UNIQUE NOT NULL,
DEPT_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE "DEPARTMENT" (
D_ID INT PRIMARY KEY,
D_NAME VARCHAR(100)
);

INSERT INTO STUDENTS VALUES
(101,'ANJAN HATAl','CSE'),
(102,'NILANJAN NATH','AIML'),
(103,'SATYABRATO ROY','SE'),
(104,'SUBRATA DAS','SE');

SELECT * FROM STUDENTS;

INSERT INTO DEPARTMENT VALUES
(201,'CSE'),
(301,'AIML'),
(401,'BBN'),
(501,'ECE');

SELECT * FROM DEPARTMENT;

SELECT S_NAME, D_ID FROM STUDENTS INNER JOIN
DEPARTMENT WHERE STUDENTS.DEPT_NAME = DEPARTMENT.DEPT_NAME;

SELECT S_NAME FROM STUDENTS INNER JOIN DEPARTMENT
WHERE S_ID = 201 AND STUDENT.DEPT_NAME = DEPARTMENT.DEPARTMENT_NAME;

SELECT S_NAME, D_ID FROM STUDENTS LEFT JOIN DEPARTMENT
ON STUDENTS.DEPT_NAME = DEPARTMENT.D_NAME;

SELECT S_NAME, S_ID FROM STUDENTS JOIN DEPARTMENT
ON STUDENTS.DEPT_NAME = DEPARTMENT.DEPT_NAME;

SELECT S_NAME, D_ID FROM STUDENTS RIGHT JOIN DEPARTMENT
ON STUDENTS.DEPT_NAME = DEPARTMENT.DEPT_NAME;

SELECT S_NAME, S_ID FROM NATURAL JOIN DEPARTMENT
WHERE STUDENTS.DEPT_NAME = DEPARTMENT.DEPT_NAME;
