CREATE TABLE DEPARTMENT(
  DEPT_ID INT PRIMARY KEY,
  DEPT_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE EMPLOYEE(
  EMP_ID INT PRIMARY KEY,
  EMP_NAME VARCHAR(100),
  DEPT_ID INT,
  SALARY DECIMAL(10,2),
  FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);


INSERT INTO DEPARTMENT VALUES (1, 'IT');
INSERT INTO DEPARTMENT VALUES (2, 'HR');
INSERT INTO DEPARTMENT VALUES (3, 'FINANCE');
INSERT INTO DEPARTMENT VALUES (4, 'MARKETING');


INSERT INTO EMPLOYEE VALUES (101, 'A', 1, 60000);
INSERT INTO EMPLOYEE VALUES (102, 'B', 2, 45000);
INSERT INTO EMPLOYEE VALUES (103, 'C', 1, 55000);
INSERT INTO EMPLOYEE VALUES (104, 'D', 3, 70000);
INSERT INTO EMPLOYEE VALUES (105, 'E', 4, 48000);
INSERT INTO EMPLOYEE VALUES (106, 'S', 1, 52000);
INSERT INTO EMPLOYEE VALUES (107, 'D', 2, 35000);


COMMIT;

DECLARE 
    V_EMPLOYEE EMPLOYEE.EMP_NAME%TYPE;
BEGIN 
    SELECT EMP_NAME INTO V_EMPLOYEE 
    FROM EMPLOYEE 
    WHERE EMP_ID = 101; 
    
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : ' || V_EMPLOYEE); 
END;
/

DECLARE 
    V_SALARY EMPLOYEE.SALARY%TYPE;
BEGIN 
    SELECT SALARY INTO V_SALARY
    FROM EMPLOYEE 
    WHERE EMP_ID = 101; 

    IF V_SALARY >= 50000 THEN
       DBMS_OUTPUT.PUT_LINE('HIGH EARNER');
    ELSE
       DBMS_OUTPUT.PUT_LINE('NORMAL EARNER');
    END IF;
END;
/
  
