CREATE TABLE BOOKS(
BookID INT PRIMARY KEY,
Title VARCHAR(100),
Author VARCHAR(100),
Genre VARCHAR(100),
Price DECIMAL(10,2)
);

CREATE TABLE MEMBERS(
MemberID INT PRIMARY KEY,
Name VARCHAR(100),
Email VARCHAR(100) UNIQUE,
JoinDate
);

INSERT INTO BOOKS VALUES
(1,'PYTHON','NILANJAN','CODING',2000.00),
(2,'ABC','SUBRATA','FICTION',2500.00),
(3,'POQ','ANJAN','MEDICAL',500.00);

SELECT * FROM BOOKS;

INSERT INTO MEMBERS VALUES
(101,'NILANJAN NATH','ABC@GMAIL.COM','2025-10-06'),
(102,'ANJAN HATAL','PQR@GMAIL.COM','2023-12-10'),
(103,'RAVIKUMAR','XYZ@GMAIL.COM','2024-08-04');

SELECT * FROM MEMBERS;

SELECT Title,Price FROM BOOKS;

SELECT * FROM BOOKS WHERE Genre='FICTION';

UPDATE BOOKS SET PRICE = 320 WHERE BOOKID=1;

SELECT * FROM BOOKS;

UPDATE MEMBERS SET Email='ravikumar@gmail.com'
WHERE Name='RAVI KUMAR';

SELECT * FROM MEMBERS;

DELETE FROM BOOKS WHERE BOOKID=2;

SELECT * FROM BOOKS;

DELETE FROM MEMBERS WHERE MEMBERID=102;

SELECT * FROM MEMBERS;

ALTER TABLE BOOKS
ADD Publisher VARCHAR(100);

SELECT * FROM BOOKS;

ALTER TABLE BOOKS MODIFY Price DECIMAL(8,2);

SELECT * FROM BOOKS;

ALTER TABLE BOOKS RENAME COLUMN Genre TO Category;

SELECT * FROM BOOKS;
