CREATE TABLE  EMPLOYEE(
  EMP_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  EMAIL VARCHAR(100),
  PHONE VARCHAR(10),
  SALARY DECIMAL(10,2),
  GENDER CHAR(1),
  DEPT_ID INT
);

INSERT INTO EMPLOYEE VALUES 
(101, 'Amit', 'Verma', 'amit.v@example.com', '9876543210', 55000.00, 'M', 1), 

(102, 'Priya', 'Mehra', 'priya.m@example.com', '9123456789', 65000.00, 'F', 2), 

(103, 'Ravi', 'Singh', 'ravi.s@example.com', '9988776655', 40000.00, 'M', 1), 

(104, 'Sneha', 'Roy', 'sneha.r@example.com', '9876501234', 75000.00, 'F', 3), 

(105, 'Anil', 'Kumar', 'anil.k@example.com', '9812345678', 30000.00, 'M', 2);

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE SALARY >50000;

SELECT * FROM EMPLOYEE WHERE GENDER = "M" AND DEPT_ID = 1;

SELECT * FROM EMPLOYEE WHERE DEPT_ID = 1 OR DEPT_ID = 2;

SELECT * FROM EMPLOYEE WHERE GENDER = "F" AND NOT DEPT_ID = 2 AND SALARY >60000;

SELECT * FROM EMPLOYEE WHERE SALARY >40000 AND SALARY <70000;

SELECT * FROM EMPLOYEE WHERE GENDER = "F" AND (DEPT_ID = 2 OR DEPT_ID = 3);

SELECT * FROM EMPLOYEE WHERE SALARY <50000;

SELECT * FROM EMPLOYEE WHERE NOT GENDER = "M" AND DEPT_ID = 3;

SELECT * FROM EMPLOYEE WHERE (DEPT_ID = 1 OR DEPT_ID = 2) AND NOT GENDER = "F" AND SALARY >30000;

SELECT * FROM EMPLOYEE WHERE FIRST_NAME  LIKE  "P%";

SELECT * FROM EMPLOYEE WHERE LAST_NAME LIKE "%A";

SELECT COUNT(*) AS TOTAL_EMP FROM EMPLOYEE WHERE DEPT_ID =1 OR DEPT_ID=2;

SELECT SUM(SALARY) AS TOTAL_SALARY FROM  EMPLOYEE;

SELECT SUM(SALARY) AS TOTAL_SALARY FROM  EMPLOYEE WHERE DEPT_ID =1;

SELECT MAX(SALARY) AS MAX_MALE FROM EMPLOYEE WHERE GENDER ="M";

SELECT * FROM EMPLOYEE ORDER BY SALARY ASC ;

SELECT * FROM EMPLOYEE ORDER BY SALARY DESC ;

SELECT GENDER,COUNT(*) AS T_NUM FROM EMPLOYEE GROUP BY GENDER ;

SELECT DEPT_ID, COUNT(*) AS EMP_COUNT FROM EMPLOYEE GROUP BY DEPT_ID HAVING COUNT(*) > 1;



















