CREATE TABLE DEPARTMENT(
  DEPT_ID INT PRIMARY KEY,
  DEPT_NAME VARCHAR(100)
);

CREATE TABLE EMPLOYEE(
  EMP_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  EMAIL VARCHAR(100) NOT NULL,
  SALARY DECIMAL(10,2),
  DEPT_ID INT,
  FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)

);

INSERT DEPARTMENT VALUES
(101,'CSE'),
(102,'AIML'),
(103,'BCA'),
(104,'AIR'),
(105,'BBA');

SELECT * FROM DEPARTMENT;

INSERT EMPLOYEE VALUES
(201,'ANJAN','HATAI','ANJAN@GMAIL.COM','4000.00',104),
(202,'SUBRATA','DAS','SUBRATA@GMAIL.COM','55000.00',101),
(203,'NILANJAN','NATH','NILJAN@GMAIL.COM','65000.00',102),
(204,'SATYABRATO','DUTTA','SATYABRATO@GMAIL.COM','25000.20',101),
(205,'MOTI','DAS','MOTI@GMAIL.COM','80000.80',103),
(206,'ASMIT','DAS','ASMIT@GMAIL.COM','98000.50',101),
(207,'ARIT','DAS','ARIT@GMAIL.COM','78000.36',NULL);

SELECT * FROM EMPLOYEE;

SELECT EMP_ID,FIRST_NAME,LAST_NAME,EMAIL FROM EMPLOYEE WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);

SELECT EMP_ID, SALARY FROM EMPLOYEE WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE);

SELECT DEPT_ID,  COUNT(*) AS total_employees FROM EMPLOYEE GROUP BY DEPT_ID HAVING COUNT(*) > 2;

SELECT EMP_ID,FIRST_NAME,LAST_NAME,EMAIL,SALARY,DEPT_ID FROM EMPLOYEE WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE) AND SALARY< (SELECT MAX(SALARY)FROM EMPLOYEE);

SELECT * FROM EMPLOYEE WHERE DEPT_ID NOT IN (SELECT DEPT_ID FROM EMPLOYEE WHERE SALARY <20000 AND DEPT_ID IS NOT NULL);











