CREATE TABLE DEPARTMENT (
  DEPT_ID INT PRIMARY KEY,
  DEPT_NAME VARCHAR(100)
);

CREATE TABLE EMPLOYEE(
  EMP_ID INT PRIMARY KEY,
  FRIST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  SALARY DECIMAL(10,2),
  GENDER VARCHAR(1),
  DEPT_ID INT,
  FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT (DEPT_ID)
);

INSERT INTO DEPARTMENT VALUES
(101,'CSE'),
(102,'AIML'),
(103,'BBA');
SELECT * FROM DEPARTMENT;

INSERT INTO EMPLOYEE VALUES
(201,'ANJAN','HATAI',45000.00,'M',101),
(301,'NILANJAN','NATH',55000.00,'M',102),
(401,'SUBRATA','DAS',35000.00,'M',103),
(501,'SATYA','DUTTA',75000.00,'F',101);
SELECT * FROM EMPLOYEE;

SELECT EMPLOYEE.FRIST_NAME, EMPLOYEE.LAST_NAME, DEPARTMENT.DEPT_NAME FROM EMPLOYEE INNER JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;
SELECT EMPLOYEE.FRIST_NAME, EMPLOYEE.LAST_NAME, DEPARTMENT.DEPT_NAME FROM EMPLOYEE LEFT JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID UNION
SELECT EMPLOYEE.FRIST_NAME, EMPLOYEE.LAST_NAME, DEPARTMENT.DEPT_NAME FROM EMPLOYEE RIGHT JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID;
SELECT * FROM EMPLOYEE WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);
SELECT DEPARTMENT.DEPT_NAME, COUNT(EMPLOYEE.EMP_ID) AS NUMBER_OF_EMPLOYEES FROM EMPLOYEE INNER JOIN DEPARTMENT 
ON EMPLOYEE.DEPT_ID = DEPARTMENT.DEPT_ID GROUP BY DEPARTMENT.DEPT_ID, DEPARTMENT.DEPT_NAME HAVING COUNT(EMPLOYEE.EMP_ID) > 1;
SELECT * FROM EMPLOYEE E1 WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE E2 WHERE E1.DEPT_ID = E2.DEPT_ID);
